# Generated by Django 4.0.4 on 2022-05-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[{'Fulfilled', 'f'}, {'Unfulfilled', 'u'}], default='f', max_length=255),
        ),
    ]
