# Generated by Django 4.0.4 on 2022-05-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('unFUL', 'Unfulfilled'), ('FUL', 'Fulfilled')], default='unFUL', max_length=255),
        ),
    ]
