version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command:  bash -c "python /app/task/manage.py migrate --noinput &&
              python /app/task/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/task
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: